/*
 Navicat Premium Data Transfer

 Source Server         : 慧构云-持云mes-测试环境
 Source Server Type    : MySQL
 Source Server Version : 50730
 Source Host           : 47.101.55.36:3306
 Source Schema         : pcmaster_org

 Target Server Type    : MySQL
 Target Server Version : 50730
 File Encoding         : 65001

 Date: 16/09/2020 11:05:57
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for sys_menu
-- ----------------------------
DROP TABLE IF EXISTS `sys_menu`;
CREATE TABLE `sys_menu` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdByName` varchar(255) DEFAULT NULL,
  `dateCreated` datetime DEFAULT NULL,
  `dateModified` datetime DEFAULT NULL,
  `modifiedBy` varchar(255) DEFAULT NULL,
  `modifiedByName` varchar(255) DEFAULT NULL,
  `org_id` bigint(20) DEFAULT NULL,
  `authMark` bit(1) DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `index_name` varchar(255) DEFAULT NULL,
  `parentId` bigint(20) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `app_id` int(11) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `flag` bit(1) DEFAULT NULL,
  `path` varchar(255) DEFAULT NULL,
  `component` varchar(255) DEFAULT NULL,
  `is_tab` bit(1) DEFAULT NULL,
  `is_route` bit(1) DEFAULT NULL,
  `i_frame` bit(1) DEFAULT NULL,
  `hidden` bit(1) DEFAULT b'0',
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=269 DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of sys_menu
-- ----------------------------
BEGIN;
INSERT INTO `sys_menu` VALUES (1, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-third-example', 'example', 0, '样例模块', 0, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'example');
INSERT INTO `sys_menu` VALUES (2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'formExample', 1, '表单样例', 1, 1, '1', b'1', '/example/formExample', 'index/example/FormExample.vue', b'1', b'0', b'0', b'0', 'formExample');
INSERT INTO `sys_menu` VALUES (3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'tableExample', 21, '表格样例', 2, 1, '1', b'1', '/example/tableExample', 'index/example/TableExample.vue', NULL, b'0', b'0', b'0', 'tableExample');
INSERT INTO `sys_menu` VALUES (4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'tableExample:query', 3, '查看', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'tableExample:query');
INSERT INTO `sys_menu` VALUES (5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'tableExample:edit', 3, '编辑', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'tableExample:edit');
INSERT INTO `sys_menu` VALUES (6, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-setting', 'system', 0, '系统管理', 990, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'system');
INSERT INTO `sys_menu` VALUES (7, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'orgManage', 6, '组织管理', 991, 1, '1', b'1', '/system/orgManage', 'index/system/user/OrgManage.vue', b'1', b'0', b'0', b'0', 'orgManage');
INSERT INTO `sys_menu` VALUES (8, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'groupManage', 6, '角色管理', 992, 1, '1', b'1', '/system/groupManage', 'index/system/user/GroupManage.vue', b'1', b'0', b'0', b'0', 'groupManage');
INSERT INTO `sys_menu` VALUES (9, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'userManage', 6, '用户管理', 993, 1, '1', b'1', '/system/userManage', 'index/system/user/UserManage.vue', b'1', b'0', b'0', b'0', 'userManage');
INSERT INTO `sys_menu` VALUES (14, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orgManage:edit', 7, '编辑', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orgManage:edit');
INSERT INTO `sys_menu` VALUES (15, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-third-basic', 'basic', 0, '基础数据', 10, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'basic');
INSERT INTO `sys_menu` VALUES (16, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', '', 'LogView', 15, '操作日志', 11, 1, '1', b'1', '/sys/LogView', 'index/basic/sys/LogView.vue', b'1', b'0', b'0', b'0', 'LogView');
INSERT INTO `sys_menu` VALUES (17, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'factoryManagement', 15, '工厂管理', 12, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'factoryManagement');
INSERT INTO `sys_menu` VALUES (18, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'prodLineNew', 17, '产线管理', 0, 1, '1', b'1', '/basic/prodline/prodLineNew', 'index/basic/prodline/ProdLineNew.vue', b'1', b'0', b'0', b'0', 'prodLineNew');
INSERT INTO `sys_menu` VALUES (19, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'prodLineNew:newEdit', 18, '新建/编辑', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'prodLineNew:newEdit');
INSERT INTO `sys_menu` VALUES (20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'prodLineNew:delete', 18, '删除', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'prodLineNew:delete');
INSERT INTO `sys_menu` VALUES (21, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'secExample', 1, '二级菜单样例', 2, 1, '1', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'secExample');
INSERT INTO `sys_menu` VALUES (22, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'echartsExample', 21, '图表样例', 1, 1, '1', b'1', '/example/echartsExample', 'index/example/EchartsExample.vue', b'1', b'0', b'0', b'0', 'echartsExample');
INSERT INTO `sys_menu` VALUES (23, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'plateManage', 17, '模台管理', 1, 1, '1', b'1', '/basic/plate/plateManage', 'index/basic/plate/PlateManage.vue', b'1', b'0', b'0', b'0', 'plateManage');
INSERT INTO `sys_menu` VALUES (24, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'plateManage:newDelete', 23, '删除', 14, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'plateManage:newDelete');
INSERT INTO `sys_menu` VALUES (25, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'stockManage', 17, '库区管理', 2, 1, '1', b'1', '/basic/yard/stockManage', 'index/basic/yard/StockManage.vue', b'1', b'0', b'0', b'0', 'stockManage');
INSERT INTO `sys_menu` VALUES (26, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'shelfManage', 17, '货架管理', 3, 1, '1', b'1', '/basic/yard/shelfManage', 'index/basic/yard/ShelfManage.vue', b'1', b'0', b'0', b'0', 'shelfManage');
INSERT INTO `sys_menu` VALUES (27, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'stockManage:newDelete', 25, '删除', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'stockManage:newDelete');
INSERT INTO `sys_menu` VALUES (28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'shelfManage:newDelete', 26, '删除', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'shelfManage:newDelete');
INSERT INTO `sys_menu` VALUES (29, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'rawMaterialManagement', 15, '编码管理', 13, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'rawMaterialManagement');
INSERT INTO `sys_menu` VALUES (30, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productTypeList', 15, '构件类型管理', 14, 1, '1', b'1', '/basic/project/productTypeList', 'index/basic/project/ProductTypeList.vue', b'1', b'0', b'0', b'0', 'productTypeList');
INSERT INTO `sys_menu` VALUES (31, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'fhManage', 15, '订单发货管理', 15, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'fhManage');
INSERT INTO `sys_menu` VALUES (32, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'materialStorageList', 29, '物料编码', 0, 1, '1', b'1', '/basic/materialStorage/materialStorageList', 'index/basic/materialStorage/MaterialStorageList.vue', b'1', b'0', b'0', b'0', 'materialStorageList');
INSERT INTO `sys_menu` VALUES (33, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'optionUnits', 29, '计量单位', 1, 1, '1', b'1', '/basic/materialStorage/optionUnitsMange', 'index/basic/materialStorage/OptionUnitsList.vue', b'1', b'0', b'0', b'0', 'optionUnits');
INSERT INTO `sys_menu` VALUES (34, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'supplier', 29, '供应商管理', 2, 1, '1', b'1', '/basicdata/supplier', 'index/basic/materialStorage/SupplierList.vue', b'1', b'0', b'0', b'0', 'supplier');
INSERT INTO `sys_menu` VALUES (35, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'categoryListTree', 29, '物料类别管理', 3, 1, '1', b'1', '/basic/materialStorage/categoryListTree', 'index/basic/materialStorage/CategoryListTree.vue', b'1', b'0', b'0', b'0', 'categoryListTree');
INSERT INTO `sys_menu` VALUES (36, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'qualityInspectionManage', 31, '质检管理', 0, 1, '1', b'1', '/basic/yard/qualityInspectionManage', 'index/basic/yard/QualityInspection.vue', b'1', b'0', b'0', b'0', 'qualityInspectionManage');
INSERT INTO `sys_menu` VALUES (37, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'qualityInspectionManage2', 31, '物流管理', 1, 1, '1', b'1', '/basic/yard/qualityInspectionManage2', 'index/basic/yard/QualityInspection2.vue', b'1', b'0', b'0', b'0', 'qualityInspectionManage2');
INSERT INTO `sys_menu` VALUES (38, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'deptManage', 31, '部门管理', 2, 1, '1', b'1', '/system/deptTreeManage', 'index/system/user/DeptTreeManage.vue', b'1', b'0', b'0', b'0', 'deptManage');
INSERT INTO `sys_menu` VALUES (39, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'teamInfoManage', 31, '班组管理', 3, 1, '1', b'1', '/basic/team/teamInfoManage', 'index/basic/team/TeamInfoManage.vue', b'1', b'0', b'0', b'0', 'teamInfoManage');
INSERT INTO `sys_menu` VALUES (40, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-third-material', 'material', 0, '原料管理', 100, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'material');
INSERT INTO `sys_menu` VALUES (41, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'receivingManagement', 40, '收料管理', 0, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'receivingManagement');
INSERT INTO `sys_menu` VALUES (42, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'materialManagement', 40, '领料管理', 1, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'materialManagement');
INSERT INTO `sys_menu` VALUES (43, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'deliverymaterialPlanList', 40, '领料计划', 2, 1, '1', b'1', '/material/deliveryPlan/deliverymaterialPlanList', 'index/material/deliveryPlan/DeliverymaterialPlanList.vue', b'1', b'0', b'0', b'0', 'deliverymaterialPlanList');
INSERT INTO `sys_menu` VALUES (44, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'turnoverDetailReportForms', 40, '进出明细', 3, 1, '1', b'1', '/material/deliveryPlan/deliverymaterialPlanList', 'index/material/deliveryPlan/DeliverymaterialPlanList.vue', b'1', b'0', b'0', b'0', 'turnoverDetailReportForms');
INSERT INTO `sys_menu` VALUES (45, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'inventoryList', 40, '原料库存', 4, 1, '1', b'1', '/material/deliveryOrder/inventoryList', 'index/material/inventory/InventoryList.vue', b'1', b'0', b'0', b'0', 'inventoryList');
INSERT INTO `sys_menu` VALUES (46, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'turnoverDetailsList', 41, '磅单收料', 0, 1, '1', b'1', '/material/turnoverDetailsList', 'index/material/TurnoverDetailsList.vue', b'1', b'0', b'0', b'0', 'turnoverDetailsList');
INSERT INTO `sys_menu` VALUES (47, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'turnoverRecordList', 41, '收料单收料', 1, 1, '1', b'1', '/material/turnoverRecordList', 'index/material/TurnoverRecordList.vue', b'1', b'0', b'0', b'0', 'turnoverRecordList');
INSERT INTO `sys_menu` VALUES (48, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'turnoverCheckList', 41, '原料检验', 2, 1, '1', b'1', '/material/turnoverCheckList', 'index/material/TurnoverCheckList.vue', b'1', b'0', b'0', b'0', 'turnoverCheckList');
INSERT INTO `sys_menu` VALUES (49, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'deliveryOrderList', 42, '领料申请', 0, 1, '1', b'1', '/material/deliveryOrder/deliveryOrderList', 'index/material/deliveryOrder/DeliveryOrderList.vue', b'1', b'0', b'0', b'0', 'deliveryOrderList');
INSERT INTO `sys_menu` VALUES (50, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'deliveryOrderApproveList', 42, '领料审批', 1, 1, '1', b'1', '/material/deliveryOrder/deliveryOrderApproveList', 'index/material/deliveryOrder/DeliveryOrderApproveList.vue', b'1', b'0', b'0', b'0', 'deliveryOrderApproveList');
INSERT INTO `sys_menu` VALUES (51, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'turnoverDetailsList:edit', 46, '编辑', 0, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'turnoverDetailsList:edit');
INSERT INTO `sys_menu` VALUES (52, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'turnoverDetailsList:delete', 46, '刪除', 1, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'turnoverDetailsList:delete');
INSERT INTO `sys_menu` VALUES (53, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'turnoverRecordList:edit', 47, '编辑', 0, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'turnoverRecordList:edit');
INSERT INTO `sys_menu` VALUES (54, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'turnoverRecordList:delete', 47, '刪除', 1, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'turnoverRecordList:delete');
INSERT INTO `sys_menu` VALUES (55, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-menu', 'project', 0, '项目管理', 200, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'project');
INSERT INTO `sys_menu` VALUES (56, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'projectsMaintenance', 55, '项目维护', 0, 1, '1', b'1', '/project/projectsMaintenance', 'index/project/projectsMaintenance/ProjectsMaintenance.vue', b'1', b'0', b'0', b'0', 'projectsMaintenance');
INSERT INTO `sys_menu` VALUES (57, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'productsMaintenance', 55, '构件维护', 1, 1, '1', b'1', '/project/productMaintenance', 'index/project/productMaintenance/ProductsMaintenance.vue', b'1', b'0', b'0', b'0', 'productsMaintenance');
INSERT INTO `sys_menu` VALUES (58, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'moldsMaintenance', 55, '模具维护', 2, 1, '1', b'1', '/project/moldMaintenance', 'index/project/moldMaintenance/MoldsMaintenance.vue', b'1', b'0', b'0', b'0', 'moldsMaintenance');
INSERT INTO `sys_menu` VALUES (59, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'planFloor', 55, '楼层形象表', 3, 1, '1', b'1', '/project/planFloor', 'index/project/planFloor/PlanFloor.vue', b'1', b'0', b'0', b'0', 'planFloor');
INSERT INTO `sys_menu` VALUES (60, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productMaterialChange', 55, 'BOM变更查询', 4, 1, '1', b'1', '/project/productChange', 'index/project/productChange/ProductChange.vue', b'1', b'0', b'0', b'0', 'productMaterialChange');
INSERT INTO `sys_menu` VALUES (61, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-s-order', 'order', 0, '生产管理', 300, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'order');
INSERT INTO `sys_menu` VALUES (62, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'MPSManageForWX', 61, '生产计划', 0, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'MPSManageForWX');
INSERT INTO `sys_menu` VALUES (63, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'plannedProduction', 61, '模台计划', 1, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'plannedProduction');
INSERT INTO `sys_menu` VALUES (64, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'MPSManage', 61, '外协管理', 2, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'MPSManage');
INSERT INTO `sys_menu` VALUES (65, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'platePlanProductDetails', 61, '构件二维码', 3, 1, '1', b'1', '/po/platePlan/productDetails', 'index/po/ProductDetailInfoList.vue', b'1', b'1', b'0', b'0', 'platePlanProductDetails');
INSERT INTO `sys_menu` VALUES (66, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'orderManageNoProject', 62, '周生产计划WPS', 0, 1, '1', b'1', '/po/orderManageNoProject', 'index/po/OrderManageNoProject.vue', b'1', b'0', b'0', b'0', 'orderManageNoProject');
INSERT INTO `sys_menu` VALUES (67, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orderManageNoProject:oneKeyOrderOut', 66, '一键产出', 0, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orderManageNoProject:oneKeyOrderOut');
INSERT INTO `sys_menu` VALUES (68, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'workOrder', 62, '日生产计划DPS', 1, 1, '1', b'1', '/po/workOrder', 'index/po/OrderWorkList.vue', b'1', b'0', b'0', b'0', 'workOrder');
INSERT INTO `sys_menu` VALUES (69, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'orderTrackForWx', 62, '计划跟踪', 2, 1, '1', b'1', '/po/orderTrack', 'index/po/OrderTrack.vue', b'1', b'0', b'0', b'0', 'orderTrackForWx');
INSERT INTO `sys_menu` VALUES (70, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'orderTrackConcrete', 62, '计划进度', 3, 1, '1', b'1', '/po/orderTrackConcrete', 'index/po/OrderTrackConcret.vue', b'1', b'1', b'0', b'0', 'orderTrackConcrete');
INSERT INTO `sys_menu` VALUES (71, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'weekOrderTeamTrack', 62, '周计划完成情况', 4, 1, '1', b'1', '/po/work/teamProductsInfo', 'index/po/TeamProductsInfo.vue', b'1', b'0', b'0', b'0', 'weekOrderTeamTrack');
INSERT INTO `sys_menu` VALUES (72, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'orderManageNoSCForWx', 63, '主生产计划MPS', 0, 1, '1', b'1', '/po/orderManage', 'index/po/OrderManage.vue', b'1', b'0', b'0', b'0', 'orderManageNoSCForWx');
INSERT INTO `sys_menu` VALUES (73, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'platePlanManage', 63, '楼栋楼层排产', 1, 1, '1', b'1', '/po/platePlanManage', 'index/po/PlatePlanManage.vue', b'1', b'0', b'0', b'0', 'platePlanManage');
INSERT INTO `sys_menu` VALUES (74, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'platePlanM2', 63, '构件类型排产', 2, 1, '1', b'1', '/po/platePlanM2', 'index/po/PlatePlanM2.vue', b'1', b'0', b'0', b'0', 'platePlanM2');
INSERT INTO `sys_menu` VALUES (75, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'platePlanSelect', 63, '模台计划查询', 3, 1, '1', b'1', '/po/platePlanSelect', 'index/po/PlatePlanSelect.vue', b'1', b'0', b'0', b'0', 'platePlanSelect');
INSERT INTO `sys_menu` VALUES (76, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'platePlanDownload', 63, '模台计划下载', 4, 1, '1', b'1', '/po/platePlan/platePlanDownload', 'index/po/PlatePlanDownload.vue', b'1', b'0', b'0', b'0', 'platePlanDownload');
INSERT INTO `sys_menu` VALUES (77, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'orderTrack', 64, '生产计划', 0, 1, '0', b'1', '/po/orderTrackForWx', 'index/po/OrderTrack.vue', b'1', b'1', b'0', b'0', 'orderTrack');
INSERT INTO `sys_menu` VALUES (78, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productInAndOutStock', 64, '构件入库', 1, 1, '1', b'1', '/po/productInAndOutStock', 'index/po/ProductDetailListForWxRk.vue', b'1', b'0', b'0', b'0', 'productInAndOutStock');
INSERT INTO `sys_menu` VALUES (79, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-view', 'check', 0, '质检管理', 400, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'check');
INSERT INTO `sys_menu` VALUES (80, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'componentInspection', 79, '构件检验', 0, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'componentInspection');
INSERT INTO `sys_menu` VALUES (81, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailList', 80, '质检记录', 0, 1, '1', b'1', '/check/productDetailList', 'index/check/ProductDetailList.vue', b'1', b'0', b'0', b'0', 'productDetailList');
INSERT INTO `sys_menu` VALUES (82, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailHiddenCheckList', 80, '隐蔽检验', 1, 1, '1', b'1', '/check/productDetailHiddenCheckList', 'index/check/ProductDetailCheckList.vue', b'1', b'0', b'0', b'0', 'productDetailHiddenCheckList');
INSERT INTO `sys_menu` VALUES (83, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailCheckList', 80, '成品检验', 3, 1, '1', b'1', '/check/productDetailCheckList', 'index/check/ProductDetailCheckList.vue', b'1', b'0', b'0', b'0', 'productDetailCheckList');
INSERT INTO `sys_menu` VALUES (84, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'componentRepair', 79, '构件返修', 1, 1, '1', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'componentRepair');
INSERT INTO `sys_menu` VALUES (85, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailHiddenCheckListReturn', 84, '隐检返修', 0, 1, '1', b'1', '/check/productDetailHiddenCheckListReturn', 'index/check/ProductDetailCheckList.vue', NULL, b'0', b'0', b'0', 'productDetailHiddenCheckListReturn');
INSERT INTO `sys_menu` VALUES (86, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailCheckListReturn', 84, '成品返修', 1, 1, '1', b'1', '/check/productDetailCheckListReturn', 'index/check/ProductDetailCheckNewList.vue', NULL, b'0', b'0', b'0', 'productDetailCheckListReturn');
INSERT INTO `sys_menu` VALUES (87, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'invoiceProductList', 84, '发货单返修', 2, 1, '1', b'1', '/plan/invoiceProductList', 'index/ship/invoice/InvoiceProductDetailList.vue', NULL, b'0', b'0', b'0', 'invoiceProductList');
INSERT INTO `sys_menu` VALUES (88, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'componentScrapping', 79, '构件报废', 2, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'componentScrapping');
INSERT INTO `sys_menu` VALUES (89, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailCheckListUselessApprove', 88, '报废审批', 0, 1, '1', b'1', '/check/productDetailCheckListUselessApprove', 'index/check/ProductDetailCheckList.vue', b'1', b'0', b'0', b'0', 'productDetailCheckListUselessApprove');
INSERT INTO `sys_menu` VALUES (90, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailCheckListUseless', 88, '报废台账', 1, 1, '1', b'1', '/check/productDetailCheckListUseless', 'index/check/ProductDetailCheckList.vue', b'1', b'1', b'0', b'0', 'productDetailCheckListUseless');
INSERT INTO `sys_menu` VALUES (91, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'certiList', 88, '合格证管理', 2, 1, '1', b'1', '/check/certiList', 'index/check/CertiList.vue', b'1', b'0', b'0', b'0', 'certiList');
INSERT INTO `sys_menu` VALUES (92, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-third-stock', 'stock', 0, '堆场管理', 500, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'stock');
INSERT INTO `sys_menu` VALUES (93, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailWaitInRecordList', 92, '待入堆场', 0, 1, '1', b'1', '/stock/productDetailWaitInRecordList', 'index/stock/ProductDetailRecordList.vue', b'1', b'0', b'0', b'0', 'productDetailWaitInRecordList');
INSERT INTO `sys_menu` VALUES (94, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'productDetailInRecordList', 92, '已入堆场', 1, 1, '1', b'1', '/stock/productDetailInRecordList', 'index/stock/ProductDetailInStockList.vue', b'1', b'0', b'0', b'0', 'productDetailInRecordList');
INSERT INTO `sys_menu` VALUES (95, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailMove', 92, '成品移库', 3, 1, '1', b'1', '/stock/productDetailMove', 'index/stock/ProductDetailMove.vue', b'1', b'0', b'0', b'0', 'productDetailMove');
INSERT INTO `sys_menu` VALUES (96, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'stockEcharts', 92, '堆场图表', 4, 1, '1', b'1', '/stock/StockEcharts', 'index/stock/StockEcharts.vue', b'1', b'0', b'0', b'0', 'stockEcharts');
INSERT INTO `sys_menu` VALUES (97, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'yardDetail', 92, '堆场明细', 5, 1, '1', b'1', '/stock/yardDetail', 'index/stock/YardDetail.vue', b'1', b'0', b'0', b'0', 'yardDetail');
INSERT INTO `sys_menu` VALUES (98, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-third-example', 'plan', 0, '发货管理', 600, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'plan');
INSERT INTO `sys_menu` VALUES (99, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'deliveryPlanList', 98, '发货计划', 0, 1, '1', b'1', '/plan/deliveryPlanList', 'index/ship/plan/DeliveryPlanList.vue', b'1', b'0', b'0', b'0', 'deliveryPlanList');
INSERT INTO `sys_menu` VALUES (100, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'invoiceNewList', 98, '发货单', 1, 1, '1', b'1', '/plan/invoiceNewList', 'index/ship/invoice/InvoiceNewList.vue', b'1', b'0', b'0', b'0', 'invoiceNewList');
INSERT INTO `sys_menu` VALUES (101, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-s-data', 'report', 0, '统计报表', 700, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'report');
INSERT INTO `sys_menu` VALUES (102, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'showMaterialCharts', 101, '原料报表', 0, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'showMaterialCharts');
INSERT INTO `sys_menu` VALUES (103, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'projectCharts', 101, '生产进度', 1, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'projectCharts');
INSERT INTO `sys_menu` VALUES (104, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'planCharts', 101, '发货报表', 2, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'planCharts');
INSERT INTO `sys_menu` VALUES (105, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'productCharts', 101, '构件报表', 3, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'productCharts');
INSERT INTO `sys_menu` VALUES (106, NULL, NULL, NULL, '2020-08-07 17:18:13', 'admin', 'admin', NULL, b'0', NULL, 'qualityCharts', 101, '质量报表', 4, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'qualityCharts');
INSERT INTO `sys_menu` VALUES (107, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'showMaterialCheckStatus', 102, '检验记录', 0, 1, '1', b'1', '/material/showMaterialCheckStatus', 'index/material/ShowMaterialCheckStatus.vue', b'1', b'1', b'0', b'0', 'showMaterialCheckStatus');
INSERT INTO `sys_menu` VALUES (108, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'materialsNeedsPreview', 102, '项目原料', 1, 1, '1', b'1', '/project/projectMaterials', 'index/project/projectMaterials/ProjectMaterials.vue', b'1', b'0', b'0', b'0', 'materialsNeedsPreview');
INSERT INTO `sys_menu` VALUES (110, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productMaterialReportForms', 102, '楼层原料', 3, 1, '1', b'1', '/project/productMaterialReport', 'index/project/productMaterialReport/ProductMaterialReportForms.vue', b'1', b'0', b'0', b'0', 'productMaterialReportForms');
INSERT INTO `sys_menu` VALUES (111, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'materialToProductByDate', 102, '原料消耗量', 4, 1, '1', b'1', '/project/materialToProductByDate', 'index/project/materialtoproductbydate/MaterialToProductByDate.vue', b'1', b'0', b'0', b'0', 'materialToProductByDate');
INSERT INTO `sys_menu` VALUES (112, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'EntryExitDetailByMonth', 102, '进出明细月报表', 5, 1, '1', b'1', '/material/deliveryOrder/entryExitDetail', 'index/material/EntryExitDetail.vue', b'1', b'0', b'0', b'0', 'EntryExitDetailByMonth');
INSERT INTO `sys_menu` VALUES (113, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'projectScheduleTrack', 103, '构件生产进度', 0, 1, '1', b'1', '/project/projectScheduleTrack', 'index/project/projectTrack/ProjectScheduleTrack.vue', b'1', b'0', b'0', b'0', 'projectScheduleTrack');
INSERT INTO `sys_menu` VALUES (116, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'orderTrackByFloor', 103, '楼层进度', 3, 1, '1', b'1', '/project/orderTrackByFloor', 'index/project/projectTrack/OrderTrackByFloor.vue', b'1', b'0', b'0', b'0', 'orderTrackByFloor');
INSERT INTO `sys_menu` VALUES (117, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'dispatchList', 104, '发货单报表', 0, 1, '1', b'1', '/charts/product/dispatchList', 'index/charts/DispatchList.vue', b'1', b'0', b'0', b'0', 'dispatchList');
INSERT INTO `sys_menu` VALUES (119, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'productCompleteNum', 105, '构件日产量报表', 1, 1, '1', b'1', '/charts/product/productCompleteNum', 'index/charts/ProductCompleteNum.vue', b'1', b'0', b'0', b'0', 'productCompleteNum');
INSERT INTO `sys_menu` VALUES (120, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'projectProductChart', 105, '项目构件数据报表', 2, 1, '1', b'1', '/charts/product/projectProductChart', 'index/charts/ProjectProductChart.vue', b'1', b'0', b'0', b'0', 'projectProductChart');
INSERT INTO `sys_menu` VALUES (121, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'qualityReport', 106, '质量日报', 0, 1, '1', b'1', '/charts/qualityReport', 'index/charts/CheckDayReport.vue', b'1', b'0', b'0', b'0', 'qualityReport');
INSERT INTO `sys_menu` VALUES (122, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orderManageNoProject:select', 66, '查询', 1, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orderManageNoProject:select');
INSERT INTO `sys_menu` VALUES (123, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'recordList', 92, '堆场履历', 2, 1, '1', b'1', '/stock/recordList', 'index/stock/YdRecordList.vue', b'1', b'0', b'0', b'0', 'recordList');
INSERT INTO `sys_menu` VALUES (124, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:print', 100, '发货单打印', NULL, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'invoiceNewList:print');
INSERT INTO `sys_menu` VALUES (125, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:certiPrint', 100, '合格证打印', NULL, 1, '2', b'1', '/stock/certiPrint', 'index/stock/CertiPrint.vue', b'0', b'1', b'0', b'0', 'certiPrint');
INSERT INTO `sys_menu` VALUES (126, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:printNew', 100, '发货单针式打印', NULL, 1, '2', b'1', '/stock/invoicePrintNew', 'index/stock/InvoicePrintNew.vue', b'0', b'1', b'0', b'0', 'invoicePrintNew');
INSERT INTO `sys_menu` VALUES (127, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:tb', 100, '同步', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'invoiceNewList:tb');
INSERT INTO `sys_menu` VALUES (128, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:hefeiPrint', 100, '合肥发货单打印', NULL, 1, '2', b'1', '/stock/hefeiPrint', 'index/stock/hefeiPrint.vue', b'1', b'1', b'0', b'0', 'hefeiPrint');
INSERT INTO `sys_menu` VALUES (129, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:htPrint', 100, '宏泰发货单打印', NULL, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'invoiceNewList:htPrint');
INSERT INTO `sys_menu` VALUES (130, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:hzPrint', 100, '杭州发货单打印', NULL, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'invoiceNewList:hzPrint');
INSERT INTO `sys_menu` VALUES (131, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:sjPrint', 100, '三杰发货单打印', NULL, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'invoiceNewList:sjPrint');
INSERT INTO `sys_menu` VALUES (132, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'platePlanProductDetails:sjPrint', 65, '三杰批量打印', NULL, 1, '2', b'1', '/po/platePlan/productDetailPrintSJ', 'index/po/ProductDetailPrintSJ.vue', b'0', b'1', b'0', b'0', 'productDetailPrintSJ');
INSERT INTO `sys_menu` VALUES (133, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'platePlanProductDetails:orgPrint', 65, '批量打印', NULL, 1, '2', b'1', '/po/platePlan/productDetailPrintsHT', 'index/po/ProductDetailPrintsHT.vue', b'0', b'1', b'0', b'0', 'productDetailPrintsHT');
INSERT INTO `sys_menu` VALUES (134, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productDetailInRecordList:backRecord', 94, '退库', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'productDetailInRecordList:backRecord');
INSERT INTO `sys_menu` VALUES (136, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'planList', 98, '发货计划-构件', 3, 1, '1', b'1', '/stock/planList', 'index/stock/PlanList.vue', b'1', b'0', b'0', b'0', 'planList');
INSERT INTO `sys_menu` VALUES (137, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'invoiceListS', 98, '发货单-构件', 4, 1, '1', b'1', '/plan/invoiceListS', 'index/ship/invoice/strong/InvoiceListS.vue', b'1', b'0', b'0', b'0', 'invoiceListS');
INSERT INTO `sys_menu` VALUES (139, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'InventorySupplementList', 41, '盘库补差', 3, 1, '1', b'1', '/material/InventorySupplementList', 'index/material/InventorySupplement/InventorySupplementList.vue', b'1', b'0', b'0', b'0', 'InventorySupplementList');
INSERT INTO `sys_menu` VALUES (140, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceListS:edit', 137, '编辑', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'invoiceListS:edit');
INSERT INTO `sys_menu` VALUES (141, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceListS:confirm', 137, '确认', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'invoiceListS:confirm');
INSERT INTO `sys_menu` VALUES (142, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'ProjectProductSendInfo', 104, '项目发货进度', 1, 1, '1', b'1', '/charts/ProjectProductSendInfo', 'index/charts/ProjectProductSendInfo.vue', b'1', b'0', b'0', b'0', 'ProjectProductSendInfo');
INSERT INTO `sys_menu` VALUES (143, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'FloorProductSendInfo', 104, '楼栋发货进度', 2, 1, '1', b'1', '/charts/FloorProductSendInfo', 'index/charts/FloorProductSendInfo.vue', b'1', b'0', b'0', b'0', 'FloorProductSendInfo');
INSERT INTO `sys_menu` VALUES (144, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'qualityMonthReport', 106, '质量月报', 0, 1, '1', b'1', '/charts/qualityMonthReport', 'index/charts/CheckMonthReport.vue', b'1', b'0', b'0', b'0', 'qualityMonthReport');
INSERT INTO `sys_menu` VALUES (145, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'materialDistributionList', 102, '原材料领料分配表', 6, 1, '1', b'1', '/report/materialDistributionList', 'index/report/MaterialDistributionList.vue', b'1', b'0', b'0', b'0', 'materialDistributionList');
INSERT INTO `sys_menu` VALUES (146, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailAllInfo', 105, '构件实绩查询', 3, 1, '1', b'1', '/charts/product/productDetails', 'index/charts/ProductDetailAllInfoList.vue', b'1', b'0', b'0', b'0', 'productDetailAllInfo');
INSERT INTO `sys_menu` VALUES (149, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productDetailJZQRCheckList', 80, '浇筑确认', 2, 1, '1', b'1', '/check/productDetailJZQRCheckList', 'index/check/ProductDetailCheckList.vue', b'1', b'0', b'0', b'0', 'productDetailJZQRCheckList');
INSERT INTO `sys_menu` VALUES (151, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'ProductTypeMaterialReport', 102, '构件类型原料报表', 8, 1, '1', b'1', '/charts/getProductTypeMaterialReport', 'index/charts/ProductTypeMaterialReport.vue', b'1', b'0', b'0', b'0', 'ProductTypeMaterialReport');
INSERT INTO `sys_menu` VALUES (152, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'LineProductChart', 105, '构件产能报表', 5, 1, '1', b'1', '/charts/getLineChartByProductTypeAndProject', 'index/charts/LineProductChart.vue', b'1', b'0', b'0', b'0', 'LineProductChart');
INSERT INTO `sys_menu` VALUES (153, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', 'el-icon-setting', 'system', 0, '系统管理', 990, 0, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'system');
INSERT INTO `sys_menu` VALUES (154, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orgManage', 165, '组织管理', 0, 0, '1', b'1', '/system/orgManage', 'index/system/user/OrgManage.vue', b'1', b'0', b'0', b'0', 'orgManage');
INSERT INTO `sys_menu` VALUES (155, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'groupManage', 165, '角色管理', 10, 0, '1', b'1', '/system/groupManage', 'index/system/user/GroupManage.vue', b'1', b'0', b'0', b'0', 'groupManage');
INSERT INTO `sys_menu` VALUES (156, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'userManage', 165, '用户管理', 5, 0, '1', b'1', '/system/userManage', 'index/system/user/UserManage.vue', b'1', b'0', b'0', b'0', 'userManage');
INSERT INTO `sys_menu` VALUES (157, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'userM2EpWx', 153, '三方用户映射', 994, 0, '1', b'1', '/user/userM2EpWx', 'index/system/user/epwx/UserM2EpWx.vue', b'1', b'0', b'0', b'0', 'userM2EpWx');
INSERT INTO `sys_menu` VALUES (158, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'setupManage', 153, '系统设置', 995, 0, '1', b'1', '/system/setupManage', 'index/system/SetupManage.vue', b'1', b'0', b'0', b'0', 'setupManage');
INSERT INTO `sys_menu` VALUES (159, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'codeExplainManage', 153, '系统代码', 996, 0, '1', b'1', '/basic/syscode/codeExplainManage', 'index/basic/syscode/CodeExplainManage.vue', b'1', b'0', b'0', b'0', 'codeExplainManage');
INSERT INTO `sys_menu` VALUES (160, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orgManage:edit', 154, '编辑', NULL, 0, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orgManage:edit');
INSERT INTO `sys_menu` VALUES (161, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'templetManage', 153, '系统模版', 998, 0, '1', b'1', '/basic/syscode/templetManage', 'index/basic/syscode/TempletManage.vue', b'1', b'0', b'0', b'0', 'templetManage');
INSERT INTO `sys_menu` VALUES (162, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'orderCodeRuleManage', 153, '单号规则', 998, 0, '1', b'1', '/basic/syscode/orderCodeRuleManage', 'index/basic/syscode/OrderCodeRuleManage.vue', b'1', b'0', b'0', b'0', 'orderCodeRuleManage');
INSERT INTO `sys_menu` VALUES (163, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'menuManage', 153, '菜单管理', 999, 0, '1', b'1', '/system/menu/menuManage', 'index/system/menu/MenuManage.vue', b'1', b'0', b'0', b'0', 'menuManage');
INSERT INTO `sys_menu` VALUES (164, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'pmManage', 153, '权限管理', 999, 0, '1', b'1', '/system/pmManage', 'index/system/user/permission/PermissionManage.vue', b'1', b'0', b'0', b'0', 'pmManage');
INSERT INTO `sys_menu` VALUES (165, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', 'el-icon-third-basic', 'basic', 0, '目录管理', 10, 0, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'basic');
INSERT INTO `sys_menu` VALUES (166, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '', 'LogView', 153, '操作日志', 11, 0, '1', b'1', '/sys/LogView', 'index/basic/sys/LogView.vue', b'1', b'0', b'0', b'0', 'LogView');
INSERT INTO `sys_menu` VALUES (167, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'productChange', 55, 'BOM变更查询-构件', 5, 1, '1', b'1', '/project/productChange', 'index/project/productChange/ProductChange.vue', b'1', b'0', b'0', b'0', 'productChange');
INSERT INTO `sys_menu` VALUES (168, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productsMaintenance:bomExcel', 57, 'BOM变更导入', 1, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'productsMaintenance:bomExcel');
INSERT INTO `sys_menu` VALUES (169, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productsMaintenance:xmlExcel', 57, '导入PXML', 2, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'productsMaintenance:xmlExcel');
INSERT INTO `sys_menu` VALUES (170, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productsMaintenance:print', 57, '上传附件', 3, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'productsMaintenance:print');
INSERT INTO `sys_menu` VALUES (171, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orderManageNoProject:addClickFB', 66, '按楼栋楼层新建', 1, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orderManageNoProject:addClickFB');
INSERT INTO `sys_menu` VALUES (172, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orderManageNoProject:addClickP', 66, '按构件类型新建', 2, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orderManageNoProject:addClickP');
INSERT INTO `sys_menu` VALUES (173, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orderManageNoProject:moveProduct', 66, '移单', 3, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orderManageNoProject:moveProduct');
INSERT INTO `sys_menu` VALUES (174, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orderManageNoProject:exportClick', 66, '导出', 4, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orderManageNoProject:exportClick');
INSERT INTO `sys_menu` VALUES (175, NULL, NULL, NULL, '2020-08-07 17:26:37', 'admin', 'admin', NULL, b'0', 'el-icon-third-material', 'semiManufacturedGoods', 0, '半成品管理', 100, 1, '0', b'1', '/Main', 'Main', b'1', b'0', b'0', b'0', 'semiManufacturedGoods');
INSERT INTO `sys_menu` VALUES (176, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'semiFinishedGoodsList', 175, '半成品编码', 0, 1, '0', b'1', '/basic/sfg/semiFinishedGoodsList', 'index/basic/sfg/SemiFinishedGoodsList.vue', b'1', b'0', b'0', b'0', 'semiFinishedGoodsList');
INSERT INTO `sys_menu` VALUES (177, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'sfgPutWarehouseList', 175, '半成品入库', 0, 1, '0', b'1', '/sfg/sfgPutWarehouseList', 'index/sfg/SfgPutWarehouseList.vue', b'1', b'0', b'0', b'0', 'sfgPutWarehouseList');
INSERT INTO `sys_menu` VALUES (178, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'sfgPickingList', 175, '半成品出库', 0, 1, '0', b'1', '/sfg/sfgPickingList', 'index/sfg/SfgPickingList.vue', b'1', b'0', b'0', b'0', 'sfgPickingList');
INSERT INTO `sys_menu` VALUES (179, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productDetailInRecordList:printRecord', 94, '打印', NULL, 1, '2', b'1', '/stock/RecordProductPrinting', 'index/stock/RecordProductPrinting.vue', b'1', b'1', b'0', b'0', 'RecordProductPrinting');
INSERT INTO `sys_menu` VALUES (180, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productDetailInRecordList:exportRecord', 94, '导出', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'productDetailInRecordList:exportRecord');
INSERT INTO `sys_menu` VALUES (181, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productDetailInRecordList:scrapRecord', 94, '报废', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'productDetailInRecordList:scrapRecord');
INSERT INTO `sys_menu` VALUES (182, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productsMaintenance:verticalExcel', 57, '竖版导入', 4, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'productsMaintenance:verticalExcel');
INSERT INTO `sys_menu` VALUES (183, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'platePlanProductDetails:xyPrint', 65, '襄阳批量打印', NULL, 1, '2', b'1', '/po/platePlan/productDetailPrintsXY', 'index/po/ProductDetailPrintsXY.vue', b'0', b'1', b'0', b'0', 'productDetailPrintsXY');
INSERT INTO `sys_menu` VALUES (184, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'checkApp', 0, '质检管理', NULL, 1, '0', b'0', '/Main', 'Main', NULL, b'0', b'0', b'0', 'checkApp');
INSERT INTO `sys_menu` VALUES (185, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-jianyan', 'hiddenCheckApp', 184, '隐检', 0, 1, '1', b'0', '/common/check/ProductDetailCheckHiddenList', NULL, NULL, b'0', b'0', b'0', 'hiddenCheckApp');
INSERT INTO `sys_menu` VALUES (186, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-fanxiuchuli', 'hiddenCheckReworkApp', 184, '隐检返修', 1, 1, '1', b'0', '/common/check/ProductDetailCheckHiddenReworkList', NULL, NULL, b'0', b'0', b'0', 'hiddenCheckReworkApp');
INSERT INTO `sys_menu` VALUES (187, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-jiaozhuzhuangtai', 'jZQRCheckApp', 184, '浇筑确认', 2, 1, '1', b'0', '/common/check/ProductDetailJZQRCheckList', NULL, NULL, b'0', b'0', b'0', 'jZQRCheckApp');
INSERT INTO `sys_menu` VALUES (188, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-chengpinjiance', 'finishedCheckApp', 184, '成品检', 3, 1, '1', b'0', '/common/check/ProductDetailCheckList', NULL, NULL, b'0', b'0', b'0', 'finishedCheckApp');
INSERT INTO `sys_menu` VALUES (189, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-fanxiuchuli', 'finishedCheckReworkApp', 184, '成品检返修', 4, 1, '1', b'0', '/common/check/ProductDetailCheckReworkList', NULL, NULL, b'0', b'0', b'0', 'finishedCheckReworkApp');
INSERT INTO `sys_menu` VALUES (190, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'stockApp', 0, '堆场管理', NULL, 1, '0', b'0', '/Main', 'Main', NULL, b'0', b'0', b'0', 'stockApp');
INSERT INTO `sys_menu` VALUES (191, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-ruku', 'warehousingApp', 190, '入库', 0, 1, '1', b'0', '/common/stock/ProductDetailStockList', NULL, NULL, b'0', b'0', b'0', 'warehousingApp');
INSERT INTO `sys_menu` VALUES (192, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-yikuicon', 'moveStockApp', 190, '移库', 1, 1, '1', b'0', '/common/stock/ProductDetailTransferList', NULL, NULL, b'0', b'0', b'0', 'moveStockApp');
INSERT INTO `sys_menu` VALUES (193, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-baofei', 'scrapStockApp', 190, '报废', 2, 1, '1', b'0', '/common/stock/ProductDetailScrapList', NULL, NULL, b'0', b'0', b'0', 'scrapStockApp');
INSERT INTO `sys_menu` VALUES (194, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'invoiceApp', 0, '发货管理', NULL, 1, '0', b'0', '/Main', 'Main', NULL, b'0', b'0', b'0', 'invoiceApp');
INSERT INTO `sys_menu` VALUES (195, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-wuliu', 'invoiceListApp', 194, '发货', 0, 1, '1', b'0', '/common/invoice/InvoiceList', NULL, NULL, b'0', b'0', b'0', 'invoiceListApp');
INSERT INTO `sys_menu` VALUES (196, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'productDetailRecordChart', 105, '构件生产履历', 9, 1, '1', b'1', '/chart/productChart/getProductRecordChartDetail', 'index/charts/product/ProductDetailRecordChart.vue', b'1', b'1', b'0', b'0', 'productDetailRecordChart');
INSERT INTO `sys_menu` VALUES (197, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'platePlanProductDetails:export', 65, '导出', 6, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'platePlanProductDetails:export');
INSERT INTO `sys_menu` VALUES (198, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orderManageNoProject:copy', 66, '复制', 6, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orderManageNoProject:copy');
INSERT INTO `sys_menu` VALUES (199, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'DailyProductionPlanReport', 105, '日计划产量报表', 9, 1, '1', b'1', '/charts/product/getDailyProductionPlanReport', 'index/charts/DailyProductionPlanReport.vue', b'1', b'0', b'0', b'0', 'DailyProductionPlanReport');
INSERT INTO `sys_menu` VALUES (200, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:yjPrint', 100, '叶集发货单打印', NULL, 1, '2', b'1', '/stock/yejiPrint', 'index/stock/yejiPrint.vue', b'0', b'1', b'0', b'0', 'yejiPrint');
INSERT INTO `sys_menu` VALUES (201, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orderManageNoProject:cancel', 66, '撤销', 5, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orderManageNoProject:cancel');
INSERT INTO `sys_menu` VALUES (202, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'workOrder:cancel', 68, '撤销', 5, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'workOrder:cancel');
INSERT INTO `sys_menu` VALUES (203, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'platePlanProductDetails:htPrint', 65, '宏泰批量打印', NULL, 1, '2', b'1', '/po/platePlan/productDetailPrintsHBHT', 'index/po/productDetailPrintsHBHT.vue', b'0', b'1', b'0', b'0', 'productDetailPrintsHBHT');
INSERT INTO `sys_menu` VALUES (204, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productDetailCheck:batchEdit', 83, '批量检验', 5, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'productDetailCheck:batchEdit');
INSERT INTO `sys_menu` VALUES (205, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'shipDailyReport', 104, '发货日报', 0, 1, '1', b'1', '/charts/ship/shipDailyReport', 'index/charts/ship/ShipDailyReport.vue', b'1', b'0', b'0', b'0', 'shipDailyReport');
INSERT INTO `sys_menu` VALUES (206, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'projectActualReport', 103, '项目进度实际', 4, 1, '1', b'1', '/project/projectActualReport', 'index/project/projectTrack/ProjectActualReport.vue', b'1', b'0', b'0', b'0', 'projectActualReport');
INSERT INTO `sys_menu` VALUES (207, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'workOrder:exportClick', 68, '导出', 0, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'workOrder:exportClick');
INSERT INTO `sys_menu` VALUES (208, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'compressiveReport', 80, '混凝土抗压强度报告', 5, 1, '1', b'1', '/check/compressiveReport', 'index/check/compressiveReport/CompressiveReport.vue', b'1', b'0', b'0', b'0', 'compressiveReport');
INSERT INTO `sys_menu` VALUES (209, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:exportQRCode', 100, '下载发货单', 5, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'invoiceNewList:exportQRCode');
INSERT INTO `sys_menu` VALUES (210, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'deliveryDetails', 104, '发货详情报表', 3, 1, '1', b'1', '/charts/delivery/deliveryDetails', 'index/charts/DeliveryDetailsReport.vue', b'1', b'0', b'0', b'0', 'deliveryDetails');
INSERT INTO `sys_menu` VALUES (211, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productsMaintenance:showSfg', 57, '查看半成品', 10, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'productsMaintenance:showSfg');
INSERT INTO `sys_menu` VALUES (212, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:findImg', 100, '查看图片', 6, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'invoiceNewList:findImg');
INSERT INTO `sys_menu` VALUES (213, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productsMaintenance:sfgPrint', 57, '半成品导入', 11, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'productsMaintenance:sfgPrint');
INSERT INTO `sys_menu` VALUES (214, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'sfg:add', 176, '新建', 0, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'sfg:add');
INSERT INTO `sys_menu` VALUES (215, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'sfg:export', 176, '下载', 2, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'sfg:export');
INSERT INTO `sys_menu` VALUES (216, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'sfg:del', 176, '删除', 3, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'sfg:del');
INSERT INTO `sys_menu` VALUES (217, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'sfg:edit', 176, '编辑', 4, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'sfg:edit');
INSERT INTO `sys_menu` VALUES (218, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'sfg:upload', 176, '导入', 4, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'sfg:upload');
INSERT INTO `sys_menu` VALUES (219, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'pr:exportSfg', 57, '下载构件半成品模版', 11, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'pr:exportSfg');
INSERT INTO `sys_menu` VALUES (220, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'trayManage', 17, '托盘维护', 4, 1, '1', b'1', '/basic/yard/trayManage', 'index/basic/yard/TrayManage.vue', b'1', b'0', b'0', b'0', 'trayManage');
INSERT INTO `sys_menu` VALUES (222, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:exportInterface', 100, '导出', 7, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'invoiceNewList:exportInterface');
INSERT INTO `sys_menu` VALUES (223, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productDetailCheck:batchEditYJ', 82, '批量检验', 5, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'productDetailCheck:batchEditYJ');
INSERT INTO `sys_menu` VALUES (224, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'ProductQrcode', 0, '扫二维码', NULL, 1, '0', b'0', '/Main', 'Main', NULL, b'0', b'0', b'0', 'ProductQrcode');
INSERT INTO `sys_menu` VALUES (225, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'ProductDetailCheckInfo', 224, '生产记录', 2, 1, '1', b'0', NULL, NULL, NULL, b'0', b'0', b'0', 'ProductDetailCheckInfo');
INSERT INTO `sys_menu` VALUES (226, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'HiddenCheckListYJ', 224, '隐检记录', 0, 1, '1', b'0', NULL, NULL, NULL, b'0', b'0', b'0', 'HiddenCheckListYJ');
INSERT INTO `sys_menu` VALUES (227, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'HiddenCheckListCPJ', 224, '成品检记录', 0, 1, '1', b'0', NULL, NULL, NULL, b'0', b'0', b'0', 'HiddenCheckListCPJ');
INSERT INTO `sys_menu` VALUES (228, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'ConcreteReport', 224, '混凝土抗压报告', 1, 1, '1', b'0', NULL, NULL, NULL, b'0', b'0', b'0', 'ConcreteReport');
INSERT INTO `sys_menu` VALUES (229, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-fanxiuchuli', 'repairStockApp', 190, '堆场返修', 1, 1, '1', b'0', '/common/stock/ProductDetailRepairList', NULL, NULL, b'0', b'0', b'0', 'repairStockApp');
INSERT INTO `sys_menu` VALUES (230, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'stackApp', 0, '堆垛管理', NULL, 1, '0', b'0', '/Main', 'Main', NULL, b'0', b'0', b'0', 'stackApp');
INSERT INTO `sys_menu` VALUES (231, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-duichangzuoye', 'scanCodeTrayingApp', 230, '构件堆垛', 0, 1, '1', b'0', '/common/stack/ScanCodeTraying', NULL, NULL, b'0', b'0', b'0', 'scanCodeTrayingApp');
INSERT INTO `sys_menu` VALUES (232, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-ruku', 'trayWarehousingApp', 230, '堆垛入库', 1, 1, '1', b'0', '/common/stack/TrayWarehousing', NULL, NULL, b'0', b'0', b'0', 'trayWarehousingApp');
INSERT INTO `sys_menu` VALUES (233, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-jiebang', 'trayUnboundApp', 230, '托盘解绑', 2, 1, '1', b'0', '/common/stack/TrayUnbound', NULL, NULL, b'0', b'0', b'0', 'trayUnboundApp');
INSERT INTO `sys_menu` VALUES (235, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'concessionRecordList', 41, '让步接收审批', 2, 1, '1', b'1', '/material/concessionRecordList', 'index/material/ConcessionRecordList.vue', b'1', b'0', b'0', b'0', 'concessionRecordList');
INSERT INTO `sys_menu` VALUES (236, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'deliveryOrderListTL', 42, '退库管理', 3, 1, '1', b'1', '/material/deliveryOrder/deliveryOrderListTL', 'index/material/deliveryOrder/DeliveryOrderListTL.vue', b'1', b'0', b'0', b'0', 'deliveryOrderListTL');
INSERT INTO `sys_menu` VALUES (237, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'prodLineManage', 17, '产线管理-编辑', 0, 1, '1', b'1', '/basic/prodline/prodLineManage', 'index/basic/prodline/ProdLineManage.vue', b'1', b'0', b'0', b'1', 'prodLineManage');
INSERT INTO `sys_menu` VALUES (238, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'invoiceEditS', 98, '发货单-构件-新建/编辑', 4, 1, '1', b'1', '/plan/invoiceEditS', 'index/ship/invoice/strong/InvoiceEditS.vue', b'0', b'1', b'0', b'1', 'invoiceEditS');
INSERT INTO `sys_menu` VALUES (239, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'invoiceNewEdit', 98, '发货单-新建/编辑', 4, 1, '1', b'1', '/plan/invoiceNewEdit', 'index/ship/invoice/InvoiceNewEdit.vue', b'0', b'1', b'0', b'1', 'invoiceNewEdit');
INSERT INTO `sys_menu` VALUES (240, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'semiFinishedGoodsInventory', 175, '半成品库存', 0, 1, '0', b'1', '/basic/sfg/semiFinishedGoodsInventory', 'index/basic/sfg/SemiFinishedGoodsInventory.vue', b'1', b'0', b'0', b'0', 'semiFinishedGoodsInventory');
INSERT INTO `sys_menu` VALUES (241, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'incomingAndOutgoingResume', 175, '出入库履历', 0, 1, '0', b'1', '/basic/sfg/incomingAndOutgoingResume', 'index/basic/sfg/IncomingAndOutgoingResume.vue', b'1', b'0', b'0', b'0', 'incomingAndOutgoingResume');
INSERT INTO `sys_menu` VALUES (242, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'floorSemiFinishedProduct', 175, '楼层半成品', 0, 1, '0', b'1', '/basic/sfg/floorSemiFinishedProduct', 'index/basic/sfg/FloorSemiFinishedProduct.vue', b'1', b'0', b'0', b'0', 'floorSemiFinishedProduct');
INSERT INTO `sys_menu` VALUES (243, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'plan:addInvoice', 136, '新建发货单', 7, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', NULL);
INSERT INTO `sys_menu` VALUES (244, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'deliveryOrderList:TL', 49, '退库', 1, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', NULL);
INSERT INTO `sys_menu` VALUES (245, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:picture', 100, '图纸导入', 8, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'invoiceNewList:picture');
INSERT INTO `sys_menu` VALUES (246, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'sfgApp', 0, '半成品管理', NULL, 1, '0', b'0', '/Main', 'Main', NULL, b'0', b'0', b'0', 'sfgApp');
INSERT INTO `sys_menu` VALUES (247, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-ruku', 'sfgPutWarehouseListApp', 246, '半成品入库', 0, 1, '1', b'0', '/common/sfg/SfgPutWarehouseList', NULL, NULL, b'0', b'0', b'0', 'sfgPutWarehouseListApp');
INSERT INTO `sys_menu` VALUES (248, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', '#iconfont-chuku', 'sfgPickingListApp', 246, '半成品出库', 1, 1, '1', b'0', '/common/sfg/SfgPickingList', NULL, NULL, b'0', b'0', b'0', 'sfgPickingListApp');
INSERT INTO `sys_menu` VALUES (251, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'turnoverDetailPriceCheck', 41, '原料核价', 5, 1, '1', b'1', '/material/TurnoverRecordListNew', 'index/material/TurnoverDetailPriceCheck.vue', b'1', b'0', b'0', b'0', 'turnoverDetailPriceCheck');
INSERT INTO `sys_menu` VALUES (252, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewList:exportCTCode', 100, '打印发货单', 9, 1, '2', b'1', NULL, NULL, b'1', b'0', b'0', b'0', 'invoiceNewList:exportCTCode');
INSERT INTO `sys_menu` VALUES (253, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'checkPicQuery', 80, '质检图片', 0, 1, '1', b'1', '/check/picQuery', 'index/check/picQuery/index.vue', b'1', b'0', b'0', b'0', 'checkPicQuery');
INSERT INTO `sys_menu` VALUES (254, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'1', NULL, 'checkProductInfo', 80, '构件信息', 7, 1, '1', b'1', '/check/checkProductInfo', 'index/check/CheckProductInfo.vue', b'1', b'1', b'0', b'1', 'checkProductInfo');
INSERT INTO `sys_menu` VALUES (255, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'invoiceNewEdit', 98, '发货单-新建/编辑', 4, 1, '1', b'1', '/plan/invoiceNewEdit', 'index/ship/invoice/InvoiceNewEdit.vue', b'0', b'1', b'0', b'1', 'invoiceNewEdit');
INSERT INTO `sys_menu` VALUES (256, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'buildingAndHouseType', 55, '户型楼栋', 4, 1, '1', b'1', '/project/buildingAndHouseType', 'index/project/projectsMaintenance/BuildingAndHouseType.vue', b'0', b'1', b'0', b'1', 'buildingAndHouseType');
INSERT INTO `sys_menu` VALUES (257, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'invoiceNewEdit:edit', 100, '编辑', NULL, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'invoiceNewEdit:edit');
INSERT INTO `sys_menu` VALUES (258, NULL, NULL, NULL, '2020-09-15 15:30:07', 'admin', 'admin', NULL, b'0', NULL, 'workOrderEdit', 62, '日生产计划DPS-新建', 6, 1, '1', b'1', '/po/workOrderEdit', 'index/po/OrderWorkEdit.vue', b'0', b'1', b'0', b'1', 'workOrderEdit');
INSERT INTO `sys_menu` VALUES (259, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'thridTempletManage', 153, '三方检验模版', 997, 0, '1', b'1', '/syscode/thridTempletManage', 'index/system/template/ThridTemplate.vue', b'1', b'0', b'0', b'0', 'thridTempletManage');
INSERT INTO `sys_menu` VALUES (260, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'generatorManage', 153, '代码生成', 997, 0, '1', b'1', '/system/generatorManage', 'index/system/generator/GeneratorManage.vue', b'1', b'0', b'0', b'0', 'generatorManage');
INSERT INTO `sys_menu` VALUES (261, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'newsPush', 153, '消息推送', 998, 0, '1', b'1', '/system/news/newsPush', 'index/system/news/NewsPush.vue', b'1', b'0', b'0', b'0', 'newsPush');
INSERT INTO `sys_menu` VALUES (262, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'timing', 153, '任务调度', 10, 0, '1', b'1', '/timing/index', 'index/system/timing/Index.vue', b'1', b'0', b'0', b'0', 'timing');
INSERT INTO `sys_menu` VALUES (263, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orgManage:del', 7, '删除', 2, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orgManage:del');
INSERT INTO `sys_menu` VALUES (264, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orgManage:del', 154, '删除', 2, 0, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orgManage:del');
INSERT INTO `sys_menu` VALUES (265, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orgManage:add', 7, '新建', 3, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orgManage:add');
INSERT INTO `sys_menu` VALUES (266, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'orgManage:add', 154, '新建', 3, 0, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'orgManage:add');
INSERT INTO `sys_menu` VALUES (267, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'deptTreeManage', 6, '部门管理', NULL, 1, '2', b'1', '/system/deptTreeManage', 'index/system/user/DeptTreeManage.vue', b'0', b'1', b'0', b'1', 'deptTreeManage');
INSERT INTO `sys_menu` VALUES (268, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'deptTreeManage', 154, '部门', NULL, 0, '2', b'1', '/system/deptTreeManage', 'index/system/user/DeptTreeManage.vue', b'0', b'1', b'0', b'0', 'deptTreeManage');
INSERT INTO `sys_menu` VALUES (269, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'floorSemiFinishedOutPut', 175, '楼层半成品出入库', 0, 1, '0', b'1', '/basic/sfg/floorSemiFinishedOutPut', 'views/index/basic/sfg/FloorSemiFinishedOutPut.vue', b'1', b'0', b'0', b'0', 'floorSemiFinishedOutPut');
INSERT INTO `sys_menu` VALUES (270, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productCheckErrorEchart', 80, '缺陷统计', 5, 1, '1', b'1', '/check/checkErrorEchart', 'index/check/ProductCheckErrorEchart.vue', b'1', b'0', b'0', b'0', 'productCheckErrorEchart');
INSERT INTO `sys_menu` VALUES (277, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'productDetailCheck:printBatchCheckExcel', 81, '成品合格证打印', 5, 1, '2', b'1', NULL, NULL, NULL, b'0', b'0', b'0', 'productDetailCheck:printBatchCheckExcel');
INSERT INTO `sys_menu` VALUES (271, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'0', NULL, 'concreteManagement', 40, '混凝土管理', 6, 1, '0', b'1', '/Empty', 'Empty', b'1', b'0', b'0', b'0', 'concreteManagement');
INSERT INTO `sys_menu` VALUES (272, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'concreteFormulation', 271, '混凝土配方', 0, 1, '1', b'1', '/material/concrete/concreteFormulation', 'index/material/concrete/ConcreteFormulation.vue', b'1', b'0', b'0', b'0', 'concreteFormulation');
INSERT INTO `sys_menu` VALUES (273, NULL, NULL, NULL, NULL, NULL, NULL, NULL, b'1', NULL, 'concreteWriteOff', 271, '混凝土核销', 1, 1, '1', b'1', '/material/concrete/concreteWriteOff', 'index/material/concrete/ConcreteWriteOff.vue', b'1', b'0', b'0', b'0', 'concreteWriteOff');

COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
