<script>
    const pageSizes = [10, 20, 50, 100, 200 ,500];
    const pageSizesMax500 = [10, 20, 50, 100, 200, 500];
    const pageSize = 20;
    const tabelHeight = 500;
    export default {
        pageSizesMax500,//每页条数列表(最大500)
        pageSizes,//每页条数列表(标准:最大200)
        pageSize,//每页条数
        tabelHeight,//表格高度
        /**
         * 订单状态
         */
        orderStatus: {
            newAdd: '新建',
            settingLine: '设置产线',
            confirm: '提交', //流程简化后，提交就是收池
            cancel: '撤销'
        },
        PRODUCT_DETAIL_STATUS:{
            DSC:'待生产',
            DYJ:'待隐检',
            DCPJ:'待成品检',
            CPRK:'成品入库',
            YRK:'已入库',
            DFH:'待发货',
            YFH:'已发货'
        },
        /**
         * 发货状态
         */
         PLAN_STATUS:{
            FHDQR:'发货待确认',
            FHYQR:'发货已确认',
         },
        /**
         * 订单错误信息
         */
        ORDER_ERR_MSG: {
            NOT_ALLOWED_EDIT: '当前计划状态不可编辑',
            NOT_ALLOWED_SETTING_LINE: '当前计划状态不可设置产线',
            NOT_ALLOWED_CANCEL: '当前计划状态不允许撤销',
            NOT_ALLOWED_CONFIRM: '当前计划状态不允许提交',
        },
        /**
         *  排产信息
         */
        PLATE_PLAN_MSG: {
            PC_NUM_IS_NULL: '请填写排产数量',
            PC_NUM_GT_ALLOW_NUM: '排产数量大于可生产量'
        },
        /**
         *  发货信息
         */
        PLAN_MSG: {
            NOT_BANDF_SELECT: '请查看选中的楼栋楼层是否赋值',
            NOT_SELECT: '请选择添加项',
            SELECT_ONE_PRINT:'只能勾选一个进行打印',
            SELECT_NOT_PRINT:'请选择打印项',
            NOT_CONFIRM:'该发货单未确认发货',
            NOT_SELECT_EXPORT:'请选择要导出的发货单',
            SELECT_ONE_EXPORT:'只能勾选一个进行导出',
            SELECT_ONE_RECEIPT:'只能勾选一个',
            NOT_SELECT_RECEIPT:'请选择发货单',
            SELECT_ONE_ADD:'只能勾选一个新增发货单',
            NOT_SELECT_ADD:'请选择发货计划',
        },
        /**
         * 项目信息
         */
        PROJECT_MSG:{
            SELECT_ONE_PROJECT:'只能选择一个项目',
            SELECT_NOT_PROJECT:'请选择项目',
            SELECTED_BATCH_PROJECT:'请至少选择一个'
        },
        PURCHASE_MSG:{
            SELECTED_ID_BEFORE:'请先选择采购单',
            SELECTED_SUPPLIER_BEFORE:'请先选择供应商',
            SELECTED_BUILDING_BEFORE:'点击左侧菜单,选择一个楼栋',
        },
        /**
         * 常见错误信息,可根据情况添加
         */
        MSG: {
            CANCEL_NOTICE: '确认撤销?该操作不可回退!',
            BIZ_NOT_ALLOWED: '当前业务规则不允许该操作，请反馈',
            UPDATE_ERR: '操作失败,请联系管理员',
            UPDATE_SUCCESS: '操作成功',
            SELECTED_ERR: '请先勾选需要操作的行',
            ADD_SUCCESS: '新建成功',
            EDIT_SUCCESS: '编辑成功',
            VALUE_NOT_CHANGE:'未做修改',
            DELETE_SUCCESS:'删除成功',
            DATA_IS_EMPTY:'数据为空,请添加',
            PROJECT_NOT_SELECT:'请先选择项目'
        },
        /**
         * 常见状态
         */
        STATUS: {
            FAILED: 'failed',
            ADD: 'add',
            UPDATE: 'update',
            SUCCESS:'success',
            WARNING:'warning',
            FAIL:'fail',

        },
        /**
         * 构件信息
         */
        PRODUCT_SFG: {
            NOT_SELECT_RECEIPT:'请选择一个构件',
            SELECT_ONE_RECEIPT:'只能勾选一个',
        },
        BUTTON_CONSTANT: [
            {
                "type":"primary",
                "icon":"el-icon-search",
                "name":"查询"
            },
            {
                "type":"primary",
                "icon":"el-icon-plus",
                "name":"新建"
            },
            {
                "type":"",
                "icon":"el-icon-edit",
                "name":"编辑"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"发货单打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"合格证打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"发货单针式打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"三杰针式打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"合肥发货单打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"叶集发货单打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"宏泰发货单打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"发货单打印A"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"杭州发货单打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"襄阳发货单打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-upload",
                "name":"导入"
            },
            {
                "type":"primary",
                "icon":"el-icon-upload",
                "name":"Excel导入"
            },
            {
                "type":"primary",
                "icon":"el-icon-download",
                "name":"导出"
            },
            {
                "type":"primary",
                "icon":"el-icon-download",
                "name":"下载发货单"
            },
            {
                "type":"primary",
                "icon":"el-icon-download",
                "name":"打印发货单"
            },
            {
                "type":"primary",
                "icon":"el-icon-download",
                "name":"下载"
            },
            {
                "type":"primary",
                "icon":"el-icon-download",
                "name":"半成品下载"
            },
            {
                "type":"primary",
                "icon":"el-icon-download",
                "name":"下载二维码"
            },
            {
                "type":"primary",
                "icon":"el-icon-upload2",
                "name":"上传"
            },
            {
                "type":"primary",
                "icon":"el-icon-circle-check",
                "name":"提交"
            },
            {
                "type":"primary",
                "icon":"el-icon-circle-check",
                "name":"保存"
            },
            {
                "type":"primary",
                "icon":"el-icon-circle-check",
                "name":"确认"
            },
            {
                "type":"danger",
                "icon":"el-icon-delete",
                "name":"删除"
            },
            {
                "type":"primary",
                "icon":"el-icon-plus",
                "name":"添加"
            },
            {
                "type":"primary",
                "icon":"el-icon-plus",
                "name":"按构件类型新建"
            },
            {
                "type":"success",
                "icon":"el-icon-plus",
                "name":"按楼栋楼层新建"
            },
            {
                "type":"warning",
                "icon":"el-icon-document-copy",
                "name":"移单"
            },
            {
                "type":"warning",
                "icon":"el-icon-connection",
                "name":"同步"
            },
            {
                "type":"warning",
                "icon":"el-icon-connection",
                "name":"同步企业微信用户"
            },
            {
                "type":"warning",
                "icon":"el-icon-connection",
                "name":"同步企业钉钉用户"
            },
            {
                "type":"success",
                "icon":"el-icon-tickets",
                "name":"排产"
            },
            {
                "type":"success",
                "icon":"el-icon-tickets",
                "name":"批量排产"
            },
            {
                "type":"success",
                "icon":"el-icon-s-fold",
                "name":"入库"
            },
            {
                "type":"success",
                "icon":"el-icon-truck",
                "name":"发货"
            },
            {
                "type":"primary",
                "icon":"el-icon-upload",
                "name":"选择导入"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"三杰批量打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"批量打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"批量打印A"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"批量打印B"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"批量打印C"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"批量打印D"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"隐检打印"
            },
            {
                "type":"success",
                "icon":"el-icon-printer",
                "name":"成品检打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"返修工单"
            },
            {
                "type":"primary",
                "icon":"el-icon-document-copy",
                "name":"复制"
            },
            {
                "type":"primary",
                "icon":"el-icon-setting",
                "name":"编辑构件"
            },
            {
                "type":"primary",
                "icon":"el-icon-guide",
                "name":"切换版本"
            },
            {
                "type":"primary",
                "icon":"el-icon-finished",
                "name":"一键产出"
            },
            {
                "type":"primary",
                "icon":"el-icon-upload",
                "name":"图纸导入"
            },
            {
                "type":"primary",
                "icon":"el-icon-upload",
                "name":"上传附件"
            },
            {
                "type":"primary",
                "icon":"el-icon-takeaway-box",
                "name":"批量操作"
            },
            {
                "type":"primary",
                "icon":"el-icon-picture-outline",
                "name":"查看图片"
            },
            {
                "type":"primary",
                "icon":"el-icon-upload",
                "name":"半成品导入"
            },
            {
                "type":"primary",
                "icon":"el-icon-document-copy",
                "name":"复制楼栋"
            },
            {
                "type":"primary",
                "icon":"el-icon-document-copy",
                "name":"复制楼层"
            },
            {
                "type":"primary",
                "icon":"el-icon-plus",
                "name":"新建发货单"
            },
            {
                "type":"primary",
                "icon":"el-icon-plus",
                "name":"退库"
            },
            {
                "type":"primary",
                "icon":"el-icon-plus",
                "name":"新增半成品"
            },
            {
                "type":"primary",
                "icon":"el-icon-takeaway-box",
                "name":"保存修改"
            },
            {
                "type":"primary",
                "icon":"el-icon-edit-outline",
                "name":"新增/编辑"
            },
            {
                "type":"danger",
                "icon":"el-icon-close",
                "name":"撤销"
            },
            {
                "type":"primary",
                "icon":"el-icon-full-screen",
                "name":"二维码"
            },
            {
                "icon":"el-icon-view",
                "name":"显示工序"
            },
            {
                "icon":"el-icon-view",
                "name":"显示工位"
            },
            {
                "type":"primary",
                "icon":"el-icon-view",
                "name":"检验"
            },
            {
                "type":"success",
                "icon":"el-icon-circle-check",
                "name":"发料"
            },
            {
                "type":"danger",
                "icon":"el-icon-circle-close",
                "name":"驳回"
            },
            {
                "type":"primary",
                "icon":"el-icon-office-building",
                "name":"户型楼栋"
            },
            {
                "type":"success",
                "icon":"el-icon-view",
                "name":"查看构件"
            },
            {
                "type":"success",
                "icon":"el-icon-view",
                "name":"查看原料"
            },
            {
                "type":"primary",
                "icon":"el-icon-s-operation",
                "name":"产线选择"
            },
            {
                "type":"primary",
                "icon":"el-icon-view",
                "name":"隐检"
            },
            {
                "type":"success",
                "icon":"el-icon-view",
                "name":"成品检"
            },
            {
                "type":"warning",
                "icon":"el-icon-refresh-left",
                "name":"返修"
            },
            {
                "type":"danger",
                "icon":"el-icon-delete-solid",
                "name":"报废"
            },
            {
                "type":"primary",
                "icon":"el-icon-s-check",
                "name":"审批"
            },
            {
                "type":"success",
                "icon":"el-icon-s-fold",
                "name":"成品入库"
            },
            {
                "type":"success",
                "icon":"el-icon-printer",
                "name":"成品检查记录表打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-printer",
                "name":"隐蔽检验记录表打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-circle-check",
                "name":"创建计划"
            },
            {
                "type":"primary",
                "icon":"el-icon-plus",
                "name":"添加用户"
            },
            {
                "type":"success",
                "icon":"el-icon-user",
                "name":"部门"
            },
            {
                "type":"primary",
                "icon":"el-icon-plus",
                "name":"添加角色"
            },
            {
                "type":"primary",
                "icon":"el-icon-key",
                "name":"修改密码"
            },
            {
                "type":"primary",
                "icon":"el-icon-key",
                "name":"权限"
            },
            {
                "type":"danger",
                "icon":"el-icon-refresh",
                "name":"报废/返修"
            },
            {
                "type":"success",
                "icon":"el-icon-view",
                "name":"查看半成品"
            },
            {
                "type":"primary",
                "icon":"el-icon-upload",
                "name":"导入图片"
            },
            {
                "type":"success",
                "icon":"el-icon-video-pause",
                "name":"恢复"
            },
            {
                "type":"warning",
                "icon":"el-icon-video-play",
                "name":"暂停"
            },
            {
                "type":"primary",
                "icon":"el-icon-time",
                "name":"设置时间"
            },
            {
                "icon":"el-icon-refresh",
                "name":"重置"
            }
            ,
            {
                "type":"success",
                "icon":"el-icon-printer",
                "name":"成品合格证打印"
            },
            {
                "type":"primary",
                "icon":"el-icon-edit-outline",
                "name":"核销"
            },
        ]
    }
</script>
