-- -------------------------------------------------------------
-- TablePlus 2.12(282)
--
-- https://tableplus.com/
--
-- Database: pcmaster_org
-- Generation Time: 2019-12-18 17:02:58.7110
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


DROP TABLE IF EXISTS `pc_group`;
CREATE TABLE `pc_group` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdByName` varchar(255) DEFAULT NULL,
  `dateCreated` datetime DEFAULT NULL,
  `dateModified` datetime DEFAULT NULL,
  `modifiedBy` varchar(255) DEFAULT NULL,
  `modifiedByName` varchar(255) DEFAULT NULL,
  `active` varchar(255) DEFAULT NULL,
  `authorities` longtext,
  `group_desc` varchar(255) DEFAULT NULL,
  `group_name` varchar(255) DEFAULT NULL,
  `org_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

INSERT INTO `pc_group` (`id`, `createdBy`, `createdByName`, `dateCreated`, `dateModified`, `modifiedBy`, `modifiedByName`, `active`, `authorities`, `group_desc`, `group_name`, `org_id`) VALUES ('1', 'admin', NULL, '2019-04-25 15:39:58', '2019-12-09 14:37:22', 'admin', '系统管理员', '是', 'example;formExample;secExample;echartsExample;tableExample;tableExample:query;tableExample:edit;basic;LogView;factoryManagement;prodLineNew;prodLineNew:newEdit;prodLineNew:delete;plateManage;plateManage:newDelete;stockManage;stockManage:newDelete;shelfManage;shelfManage:newDelete;rawMaterialManagement;materialStorageList;optionUnits;supplier;categoryListTree;productTypeList;fhManage;qualityInspectionManage;qualityInspectionManage2;deptManage;teamInfoManage;material;receivingManagement;turnoverDetailsList;turnoverDetailsList:edit;turnoverDetailsList:delete;turnoverRecordList;turnoverRecordList:edit;turnoverRecordList:delete;turnoverCheckList;materialManagement;deliveryOrderList;deliveryOrderApproveList;deliverymaterialPlanList;turnoverDetailReportForms;inventoryList;project;projectsMaintenance;productsMaintenance;moldsMaintenance;planFloor;productMaterialChange;order;MPSManageForWX;orderManageNoProject;orderManageNoProject:oneKeyOrderOut;orderManageNoProject:select;workOrder;orderTrackForWx;orderTrackConcrete;weekOrderTeamTrack;plannedProduction;orderManageNoSCForWx;platePlanManage;platePlanM2;platePlanSelect;platePlanDownload;MPSManage;orderTrack;productInAndOutStock;platePlanProductDetails;check;componentInspection;productDetailList;productDetailHiddenCheckList;productDetailCheckList;componentRepair;productDetailHiddenCheckListReturn;productDetailCheckListReturn;invoiceProductList;componentScrapping;productDetailCheckListUselessApprove;productDetailCheckListUseless;certiList;stock;productDetailWaitInRecordList;productDetailInRecordList;recordList;productDetailMove;stockEcharts;yardDetail;plan;deliveryPlanList;invoiceNewList;report;showMaterialCharts;showMaterialCheckStatus;materialsNeedsPreview;orderMaterials;productMaterialReportForms;materialToProductByDate;EntryExitDetailByMonth;projectCharts;projectScheduleTrack;projectTrack;productTrack;orderTrackByFloor;planCharts;dispatchList;productCharts;overProductList;productCompleteNum;projectProductChart;qualityCharts;qualityReport;system;orgManage;orgManage:edit;groupManage;userManage;userM2EpWx;setupManage;codeExplainManage', NULL, '系统管理员', '1');
INSERT INTO `pc_group` (`id`, `createdBy`, `createdByName`, `dateCreated`, `dateModified`, `modifiedBy`, `modifiedByName`, `active`, `authorities`, `group_desc`, `group_name`, `org_id`) VALUES ('2', 'admin', 'admin', '2019-04-26 16:21:02', '2019-12-18 15:47:51', 'admin', '系统管理员', '是', 'example;formExample;secExample;echartsExample;tableExample;tableExample:query;tableExample:edit;basic;LogView;factoryManagement;prodLineNew;prodLineNew:newEdit;prodLineNew:delete;plateManage;plateManage:newDelete;stockManage;stockManage:newDelete;shelfManage;shelfManage:newDelete;rawMaterialManagement;materialStorageList;optionUnits;supplier;categoryListTree;productTypeList;fhManage;qualityInspectionManage;qualityInspectionManage2;deptManage;teamInfoManage;material;receivingManagement;turnoverDetailsList;turnoverDetailsList:edit;turnoverDetailsList:delete;turnoverRecordList;turnoverRecordList:edit;turnoverRecordList:delete;turnoverCheckList;materialManagement;deliveryOrderList;deliveryOrderApproveList;deliverymaterialPlanList;turnoverDetailReportForms;inventoryList;project;projectsMaintenance;productsMaintenance;moldsMaintenance;planFloor;productMaterialChange;order;MPSManageForWX;orderManageNoProject;orderManageNoProject:oneKeyOrderOut;orderManageNoProject:select;workOrder;orderTrackForWx;orderTrackConcrete;weekOrderTeamTrack;plannedProduction;orderManageNoSCForWx;platePlanManage;platePlanM2;platePlanSelect;platePlanDownload;MPSManage;orderTrack;productInAndOutStock;platePlanProductDetails;check;componentInspection;productDetailList;productDetailHiddenCheckList;productDetailCheckList;componentRepair;productDetailHiddenCheckListReturn;productDetailCheckListReturn;invoiceProductList;componentScrapping;productDetailCheckListUselessApprove;productDetailCheckListUseless;certiList;stock;productDetailWaitInRecordList;productDetailInRecordList;recordList;productDetailMove;stockEcharts;yardDetail;report;showMaterialCharts;showMaterialCheckStatus;materialsNeedsPreview;orderMaterials;productMaterialReportForms;materialToProductByDate;EntryExitDetailByMonth;projectCharts;projectScheduleTrack;projectTrack;productTrack;orderTrackByFloor;planCharts;dispatchList;productCharts;overProductList;productCompleteNum;projectProductChart;qualityCharts;qualityReport;orgManage;orgManage:edit;groupManage;userManage', NULL, '试用', '1');
INSERT INTO `pc_group` (`id`, `createdBy`, `createdByName`, `dateCreated`, `dateModified`, `modifiedBy`, `modifiedByName`, `active`, `authorities`, `group_desc`, `group_name`, `org_id`) VALUES ('3', 'admin', 'admin', '2019-05-17 10:12:58', '2019-05-19 11:24:43', 'sunlichao', '孙立超', '是', 'turnoverCheckList;planFloor;platePlanSelect;platePlanDownload;platePlanProductDetails;check;productDetailList;productDetailHiddenCheckList;productDetailHiddenCheckListReturn;productDetailCheckList;productDetailCheckListReturn;productDetailCheckListUselessApprove;checkScrapped;productDetailCheckListUseless;certiList;stock;productDetailWaitInRecordList;productDetailInRecordList;productDetailMove;planList;stockEcharts;yardDetail;report;showMaterialCharts;showMaterialCheckStatus;inventoryList;materialsNeedsPreview;projectMaterials;orderMaterials;productMaterialReportForms;materialToProductByDate;projectCharts;projectScheduleTrack;projectTrack;productTrack;orderTrackByFloor;productCharts;overProductList', NULL, '质量管理', '1');
INSERT INTO `pc_group` (`id`, `createdBy`, `createdByName`, `dateCreated`, `dateModified`, `modifiedBy`, `modifiedByName`, `active`, `authorities`, `group_desc`, `group_name`, `org_id`) VALUES ('4', 'admin', 'admin', '2019-05-17 10:13:10', '2019-05-21 16:01:36', 'sunlichao', '孙立超', '是', 'prodLineNew:newEdit;codeExplainManage;productManage;productCategoriesList;productTypeManage;fhManage;qualityInspectionManage;teamInfoManage;deptManage;turnoverDetailReportForms;project;projectsMaintenance;productsMaintenance;moldsMaintenance;planFloor;order;MPSManage;orderManage;orderChooseManage;orderTrack;plateManage;platePlanManage;platePlanM2;platePlanSelect;platePlanDownload;platePlanProductDetails;productDetailList;productDetailCheckListUselessApprove;productDetailCheckListUseless;productDetailInRecordList;planList;stockEcharts;yardDetail;report;showMaterialCharts;showMaterialCheckStatus;inventoryList;materialsNeedsPreview;projectMaterials;orderMaterials;productMaterialReportForms;materialToProductByDate;projectCharts;projectScheduleTrack;projectTrack;productTrack;orderTrackByFloor;productCharts;overProductList', NULL, '项目数据管理', '1');
INSERT INTO `pc_group` (`id`, `createdBy`, `createdByName`, `dateCreated`, `dateModified`, `modifiedBy`, `modifiedByName`, `active`, `authorities`, `group_desc`, `group_name`, `org_id`) VALUES ('5', 'admin', 'admin', '2019-05-17 10:13:24', '2019-05-17 10:49:51', 'admin', 'admin', '是', 'prodLineNew;prodLineNew:newEdit;prodLineNew:delete;plateManage;plateManage:newDelete;stockManage;stockManage:newDelete;shelfManage;shelfManage:newDelete;fhManage;qualityInspectionManage;teamInfoManage;deptManage;deliveryOrderList;deliveryOrderApproveList;turnoverDetailReportForms;project;projectsMaintenance;productsMaintenance;moldsMaintenance;planFloor;order;MPSManage;orderManage;orderChooseManage;orderTrack;plateManage;platePlanManage;platePlanM2;platePlanSelect;platePlanDownload;platePlanProductDetails;check;productDetailList;productDetailHiddenCheckList;productDetailHiddenCheckListReturn;productDetailCheckList;productDetailCheckListReturn;productDetailCheckListUselessApprove;checkScrapped;productDetailCheckListUseless;certiList;stock;productDetailWaitInRecordList;productDetailInRecordList;productDetailMove;planList;stockEcharts;yardDetail;report;showMaterialCharts;showMaterialCheckStatus;inventoryList;materialsNeedsPreview;projectMaterials;orderMaterials;productMaterialReportForms;materialToProductByDate;projectCharts;projectScheduleTrack;projectTrack;productTrack;orderTrackByFloor;productCharts;overProductList', NULL, '生产管理人员', '1');
INSERT INTO `pc_group` (`id`, `createdBy`, `createdByName`, `dateCreated`, `dateModified`, `modifiedBy`, `modifiedByName`, `active`, `authorities`, `group_desc`, `group_name`, `org_id`) VALUES ('6', 'admin', 'admin', '2019-05-17 10:13:41', '2019-05-17 17:12:37', 'admin', 'admin', '是', 'plateManage;plateManage:newDelete;materialManage;materialStorageList;optionUnits;classificationList;categoryList;turnoverDetailsList;turnoverDetailsList:edit;turnoverDetailsList:delete;turnoverRecordList;turnoverRecordList:edit;turnoverRecordList:delete;deliveryOrderList;deliveryOrderApproveList;turnoverDetailReportForms;productDetailList;checkScrapped;productDetailCheckListUseless;certiList;stockEcharts;report;showMaterialCharts;showMaterialCheckStatus;inventoryList;materialsNeedsPreview;projectMaterials;orderMaterials;productMaterialReportForms;materialToProductByDate;projectCharts;projectScheduleTrack;projectTrack;productTrack;orderTrackByFloor;productCharts;overProductList', NULL, '原料库存管理', '1');
INSERT INTO `pc_group` (`id`, `createdBy`, `createdByName`, `dateCreated`, `dateModified`, `modifiedBy`, `modifiedByName`, `active`, `authorities`, `group_desc`, `group_name`, `org_id`) VALUES ('7', 'admin', 'admin', '2019-05-17 10:13:52', '2019-05-17 10:18:26', 'admin', 'admin', '是', 'stockManage;stockManage:newDelete;shelfManage;shelfManage:newDelete;fhManage;qualityInspectionManage;teamInfoManage;deptManage;platePlanProductDetails;productDetailList;productDetailCheckListUselessApprove;checkScrapped;productDetailCheckListUseless;certiList;stock;productDetailWaitInRecordList;productDetailInRecordList;productDetailMove;planList;stockEcharts;yardDetail;report;showMaterialCharts;showMaterialCheckStatus;inventoryList;materialsNeedsPreview;projectMaterials;orderMaterials;productMaterialReportForms;materialToProductByDate;projectCharts;projectScheduleTrack;projectTrack;productTrack;orderTrackByFloor;productCharts;overProductList', NULL, '堆场管理', '1');
INSERT INTO `pc_group` (`id`, `createdBy`, `createdByName`, `dateCreated`, `dateModified`, `modifiedBy`, `modifiedByName`, `active`, `authorities`, `group_desc`, `group_name`, `org_id`) VALUES ('8', 'admin', 'admin', '2019-05-17 10:14:10', '2019-12-02 14:05:09', 'admin', '系统管理员', '是', 'formExample;tableExample:select;system;orgManage;groupManage;userManage;userM2EpWx;setupManage;codeExplainManage', NULL, '管理员', '1');
INSERT INTO `pc_group` (`id`, `createdBy`, `createdByName`, `dateCreated`, `dateModified`, `modifiedBy`, `modifiedByName`, `active`, `authorities`, `group_desc`, `group_name`, `org_id`) VALUES ('9', 'admin', '系统管理员', '2019-12-03 17:40:17', '2019-12-03 17:40:17', 'admin', '系统管理员', '是', NULL, NULL, '系统管理员', '1');


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;